export const ConfigDescriptions = {
    tenantId: 'Tenant ID',
    urlId: 'URL ID',
    url: 'URL',
    hasDarkBackground: 'Page Has Dark Background',
    pageTitle: 'Page Title',
    commentCountFormat: 'Comment Count Format',
    originalReferrer: 'Original Referrer',
    hideAvatars: 'Hide Avatars',
    readonly: 'Readonly',
    inputAfterComments: 'Input After Comments',
    maxCommentCharacterLength: 'Max Comment Character Length',
    absoluteDates: 'Absolute Dates',
    hideCommentsUnderCountTextFormat: '"Hide Comments Under Count" Text Format',
    headerHTML: "Header HTML",
    debugRenderTime: "Debug Render Time",
    noStyles: "Disable Default Styling",
    allowAnon: "Allow anonymous commenting",
    noImageUploads: "No Image Uploads",
    countAll: "Include nested replies in overall count",
    showLiveRightAway: "Show Live Comments Right Away",
    sso: 'SSO',
    instanceId: 'Instance ID (random)'
};
